# Generated by Django 5.1.5 on 2025-01-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('lesson', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
