# Generated by Django 5.1.5 on 2025-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='time',
            field=models.TimeField(),
        ),
    ]
