# Generated by Django 5.1.5 on 2025-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classrooms_schedule_subject_delete_dairy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Названия предмета'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
