# Generated by Django 5.1.5 on 2025-01-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schedule_subject_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.IntegerField(verbose_name='Номер комнаты'),
        ),
        migrations.DeleteModel(
            name='Classrooms',
        ),
    ]
