# Generated by Django 5.1.5 on 2025-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(verbose_name='Комната'),
        ),
    ]
