# Generated by Django 5.1.5 on 2025-01-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
