# Generated by Django 5.1.5 on 2025-01-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_subject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
    ]
